config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  root "articles#index"

  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def index
    @articles = Article.all
  end

  def show
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.save
    redirect_to article_path(@article)
  end

  def edit
  end

  def update
    @article.update(article_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article.destroy
    redirect_to articles_path, status: :see_other
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<div class="container my-4">
  <div class="col-md-8 mx-auto">
    <h1 class="mb-4">Edit Article</h1>

    <%= form_with model: @article, local: true do |form| %>
      <div class="mb-3">
        <%= form.label :title, class: "form-label" %>
        <%= form.text_field :title, class: "form-control" %>
      </div>

      <div class="mb-3">
        <%= form.label :content, class: "form-label" %>
        <%= form.text_area :content, class: "form-control", rows: 6 %>
      </div>

      <div class="d-flex flex-column">
        <%= form.submit "Create Article", class: "btn btn-primary" %>
        <%= link_to "Back", root_path %>
      </div>
    <% end %>
  </div>
</div>

app/views/articles/index.html.erb
<div class="container my-4">

  <div class="col-md-8 mx-auto">
    <% @articles.each do |article| %>
      <article class="mb-3 pb-3 border-bottom">
        <h2 class="text-start">
          <%= link_to article.title, article_path(article), class: "text-decoration-none" %>
        </h2>
        <p class="text-start">
          <%= article.content %>
        </p>
      </article>
    <% end %>
  </div>
</div>

app/views/articles/new.html.erb
<div class="container my-4">
  <div class="col-md-8 mx-auto">
    <h1 class="mb-4">New Article</h1>

    <%= form_with model: @article, local: true do |form| %>
      <div class="mb-3">
        <%= form.label :title, class: "form-label" %>
        <%= form.text_field :title, class: "form-control" %>
      </div>

      <div class="mb-3">
        <%= form.label :content, class: "form-label" %>
        <%= form.text_area :content, class: "form-control", rows: 6 %>
      </div>
      <div class="d-flex flex-column">
        <%= form.submit "Create Article", class: "btn btn-primary" %>
        <%= link_to "Back", root_path %>
      </div>
    <% end %>
  </div>
</div>

app/views/articles/show.html.erb
<div class="container my-4">
  <div class="col-md-8 mx-auto">
    <h1 class="mb-3"><%= @article.title %></h1>

    <p class="fs-5"><%= @article.content %></p>

    <div class="d-flex gap-2 mt-4">
      <%= link_to "Edit", edit_article_path(@article), class: "btn btn-warning" %>
      <%= link_to "Back", root_path, class: "btn btn-secondary" %>
      <%= link_to "Delete", article_path(@article),
            data: { turbo_method: :delete, turbo_confirm: "Are you sure?" },
            class: "btn btn-danger" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css" 
          rel="stylesheet" 
          integrity="sha384-4Q6Gf2aSP4eDXB8Miphtr37CMZZQ5oXLH2yaXMJ2w8e2ZtHTl7GptT4jmndRuHDT" 
          crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>

    <%= yield %>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" <%= link_to "RailsWikinimous", root_path %></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
      aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="ms-auto">
        <%= link_to "New article", new_article_path, class: "btn btn-primary text-white" %>
      </div>
    </div>
  </div>
</nav>